# Use this in ~/.bashrc to read file.
# if [ -f ~/.bash_aliases ]; then
#     . ~/.bash_aliases
# fi
myuptime () {
  uptime | awk '{ print "Uptime:", $3, $4, $5 }' | sed 's/,//g'
  return;
}

alias vim='nvim'

alias volup="amixer sset Master 10%+"
alias voldown="amixer sset Master 10%-"
alias vol="amixer sset Master"

alias brightup="sudo brightnessctl set +10%"
alias brightdown="sudo brightnessctl  set 10%-"
alias bright="sudo brightnessctl set"
alias o="xdg-open"

alias tablet="python3 /home/henrik/programming/scripts/scale.py"
alias b-noise="/home/henrik/programming/scripts/brown_noise.sh"

alias nnn="nnn -e -H" 
# -e = edit in $EDITOR
# -H = show hidden
alias x="exit"
alias buildgcc="gcc -Wall -g $1 -o a.out"
alias ec="emacsclient -n"
alias lc3="/home/henrik/Documents/t2/machine/LC_3_Simulator/LC3Tools-2.0.2.AppImage"

createLatex() {
	file=$1
	filename="${file%.*}"
	outdir="out-${filename}"
	mkdir -p $outdir && pandoc $file --standalone --output $outdir/$filename.pdf #&& pdflatex -output-directory=$outdir $outdir/$filename.tex
	#find $outdir | rg .*(aux|log)$ | xargs rm
	find $outdir -type f -iname '*.pdf' | xargs xdg-open

}
zi(){
	cd $(zoxide query --list $1 | fzf)
}


upgradeAptApps() {
	sudo apt update -y && sudo apt upgrade -y
}

install() {
	sudo apt install $1
}

alias redo='sudo !!'

mkcd() { mkdir -p "$1" && cd "$1"; }

alias glogall='git log --graph --full-history --all --color --oneline'
alias ga='git add'
alias gc='git commit'
alias gpush='git push'
alias gpull='git pull'

# Full info and hidden files
alias lah='ls -lah'

alias cpscreenshot='cp "$(fd . ~/Pictures/Screenshots/ -a | tail -1)" .'

alias foxit='/home/henrik/.installedPrograms/foxitsoftware/foxitreader/FoxitReader.sh'


filepick-extension() {
	fd -e rs | fzf --preview='head -$LINES {}' -m | paste -s -d " "
}
